version: '3.8'

services:
  app:
    build: .
    ports:
      - "8989:8000"
    environment:
      - DB_HOST=113.45.191.109
      - DB_PORT=53000
      - DB_USER=memo
      - DB_PASSWORD=heKHemO6_pM0Y81sOkPMpj5nAM_eHLX62fXC36M3M1w
      - DB_NAME=app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=login_app
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
