# typings/transformers/__init__.pyi
from typing import Any

class AutoTokenizer:
    @staticmethod
    def from_pretrained(model_name: str, **kwargs: Any) -> "AutoTokenizer": ...
    def encode(self, text: str, **kwargs: Any) -> list[int]: ...
    def decode(self, tokens: list[int], **kwargs: Any) -> str: ...
